### ISSUE TITLE
Endpoint for global recent episodes.

### ISSUE THREAD

**Issue by AqilCont** [AniAPI-Team/AniAPI#10]
We are a team of developers working on an app called [Enime](https://www.github.com/Enime-Project/enime), an anime streaming and managing app, and we would like to move backend APIs to AniAPI. The only problem we face is that there's no global recent episodes endpoint, which is usually a feature of a lot of other anime streaming apps and an important feature to have in general. If you could provide us with this feature, we would be able to easily move over and spread the influence of this API while also putting it to good use.

**Comment by Dazorn96** [comment]
Implemented with PR #12
