### ISSUE TITLE
Fetch with a list of IDs and simplify API.

### ISSUE THREAD

**Issue by AqilCont** [AniAPI-Team/AniAPI#11]
The current `/anime/:id` endpoint is very restricting for us as there's only one ID we can provide. We would need information on many anime at once in a basic service, and requesting all of them separately would be very tedious for both the API and us. The other listed `/anime/` endpoint can't provide list based ID params either.

A possible solution I thought of for this is to take off the `/anime/:id` endpoint and just add an `id` param to the existing `/anime/` endpoint, while enabling list support for it and all other id based params. This would make the API simpler and would offer a greater deal of support.

This could also be done with all other endpoints.

**Comment by Dazorn96** [comment]
Implemented with PR #12
