### ISSUE TITLE
Implement data scraping on the anitube website

### ISSUE THREAD

**Issue by renanzdm** [AniAPI-Team/AniAPI#28]
First of all, thank you for the work you are doing, I would very much like you to implement another site, as I live in Brazil and would like to have content in Portuguese if possible.
This would be the site: https://anitube.cx/

**Comment by Dazorn96** [comment]
Hi, I am getting a 1020 cloudflare error... probably because the website's master is blocking external traffic (from other regions).
I'll need to use a VPN, so the developing of the feature could have a slow down ;)

**Comment by renanzdm** [comment]
No problem, I'm trying to develop an api for data scraping in JavaScript, but it's not my area. I was successful using it on localhost but hosting it on heroku, I'm investigating what it could be but I'm afraid it's something related to the site

**Comment by renanzdm** [comment]
maybe this site https://animesbr.biz/

**Comment by Dazorn96** [comment]
Actually AniAPI can reach only one website: https://animesonlinebr.co/.
This website has a strong server-side check on navigation and I can't find a way to overpass it.
A brazilian website will be implemented in future, if will be provided a implementable one.
