### ISSUE TITLE
prequel and sequel are in a loop 

### ISSUE THREAD

**Issue by joellui** [AniAPI-Team/AniAPI#42]
Anime - Saiyuki

2.1	Gensomaden Saiyuki (2000–01)
2.2	Saiyuki Reload (2003–04)
2.3	Saiyuki Reload GunLock (2004)
2.4	Saiyuki Reload Blast (2017)
2.5	Saiyuki Reload: Zeroin (2022)

This is the following sequence for anime.

The issue is in the sequence of the last two anime are in a loop anime_id: 3749 & anime_id: 2930

**Comment by Dazorn96** [comment]
This problem is related to AniList. No further investigation needed.
