### ISSUE TITLE
[Fix] anime list response returns incorrect pagination info 

### ISSUE THREAD

**Issue by AlmasShagdarov** [AniAPI-Team/AniAPI#45]
https://api.aniapi.com/v1/anime?formats=0&formats=1&formats=2&formats=3&formats=4&formats=5&locale=en&page=2&perPage=20&sort_fields=season_year&sort_directions=-1 
Response last_page 128

https://api.aniapi.com/v1/anime?formats=0&formats=1&formats=2&formats=3&formats=4&formats=5&year=2021&locale=en&page=3&perPage=20&sort_fields=season_year&sort_directions=-1 
Response last_page is 4

**Comment by Dazorn96** [comment]
@AlmasShagdarov i just noticed the `year=2021` filter in the second request. That's why you get only 4 pages, instead 129.
Closed.
