### ISSUE TITLE
[Bug] Some Anilist's anime are not collected

### ISSUE THREAD

**Issue by AITYunivers** [AniAPI-Team/AniAPI#54]
Nekopara is an anime listed on both MyAnimeList and Anilist yet trying
`https://api.aniapi.com/v1/anime?anilist_id=106863`
or
`https://api.aniapi.com/v1/anime?mal_id=38924`
just doesn't say anything, but oddly enough the OVAs and the specials show when I try
`https://api.aniapi.com/v1/anime?title=Nekopara`
but yet the actual anime doesn't?

Seems to happen with a lot of anime.

**Comment by AITYunivers** [comment]
Seems like it's actually an issue with a ton of anime after a bit of testing.

**Comment by Dazorn96** [comment]
Thank you @AITYunivers for the report!
I'll start investigate on what could be the issue

**Comment by Dazorn96** [comment]
@AITYunivers the anime `Nekopara` contains genre `Nudity`, which is blocked by default because `nsfw` is `false` (by default).
You need to also add this parameter, like this: `https://api.aniapi.com/v1/anime?anilist_id=106863&nsfw=true`

**Comment by AITYunivers** [comment]
OHHHHH Okaayyy yeah yeah, that makes sense. Thanks man.
