### ISSUE TITLE
[Feature Request] Make it show their actual English names.

### ISSUE THREAD

**Issue by AITYunivers** [AniAPI-Team/AniAPI#57]
Can you make it so English is their actual English names (If applicable) instead of their Japanese names in English characters?

For example
`Love, Chunibyo & Other Delusions!`
instead of
`Chuunibyou demo Koi ga Shitai!`

**Comment by Dazorn96** [comment]
@AITYunivers this is already planned to be implemented within this [card](https://github.com/AniAPI-Team/AniAPI/projects/4#card-72551907)

**Comment by AITYunivers** [comment]
That link sends me to a blank page and I see nothing about it in the Projects page. Perhaps the card is private?
