### ISSUE TITLE
Mapping all episodes

### ISSUE THREAD

**Issue by joellui** [AniAPI-Team/AniAPI#60]
Mapping all episodes to their respective anime. 
Especially for **GoGoAnime**.

Eg OnePiece for Gogo anime is only showing 14 episodes in total.

**Comment by joellui** [comment]
Can u make this bug a height priority because it is making the API look bad and unusable

**Comment by Dazorn96** [comment]
> Can u make this bug a height priority because it is making the API look bad and unusable

Actually, I am working on a new scraper engine.
Fixing actual engine would be a loss of time.
Just wait a bit more ;)
