### ISSUE TITLE
[Feature Request] Have extra video info on episode

### ISSUE THREAD

**Issue by nekitbr** [AniAPI-Team/AniAPI#63]
Return video size (eg. `... , viewport: { x: 1920 , y: 1080 } , ...` )
Can be linked to #61

**Comment by Dazorn96** [comment]
> Return video size (eg. `... , viewport: { x: 1920 , y: 1080 } , ...` ) Can be linked to #61

Would this be useful on client-side?
I mean... you just need a `quality` field, which specify the video streaming quality, for example `480`, `720`, `1080`.

Let me know if your idea involves something in particular.

**Comment by nekitbr** [comment]
I had an idea that was OK and would work well, but thinking it through, no one watches video with the normal player if a fullscreen option is available, and if the service owner cares enough about his stream quality the fullscreen option is certainly enabled, so not even worth talking about it (unless...).
Unless you have another idea with that topic, this can be closed. :)
