### ISSUE TITLE
Unable to stream m3u8 streaming video URLs

### ISSUE THREAD

**Issue by adarsh-technocrat** [AniAPI-Team/AniAPI#89]
Hi everyone I am making a desktop application for streaming Anime but unfortunately I am not able to stream this m3u8 video URL.

```json
            {
                "anime_id": 1,
                "number": 1,
                "title": "Episode 1",
                "video": "https://yqwdm.vizcloud.xyz/simple/EqPFI_8QBAro1HhYl67rC8Eur1xdu_ewAwN7rqk+wYMnU94US2El/br/list.m3u8",
                "video_headers": {
                    "referer": "https://vidstream.pro/info/XEYLM4M4WPVN?domain=gogoanime.lol&skey=dcb0a59359d3f732f8b545fd2908e497"
                },
                "format": "m3u8",
                "locale": "en",
                "is_dub": false,
                "id": 1
            },

```

This is what my current application looks like : - 

<img align="center" src="https://user-images.githubusercontent.com/47661086/158646722-118be527-1e9c-48e9-a811-f7101b27a0c3.png" width="100%"/>
</br>
<img align="center" src="https://user-images.githubusercontent.com/47661086/162567918-d8a7ef7f-a153-4bc6-aaa1-d75f6e0a5792.png" width="100%"/>
  

Need help with how I can play these video URLs,  event if I paste the URL's in  Browser it's not playing.

**Comment by Dazorn96** [comment]
@adarsh-technocrat check our [FAQ](https://discord.com/channels/864487732121960488/951776400313040896) channel on discord ;)
