### ISSUE TITLE
Documentation Not working

### ISSUE THREAD

**Issue by EL-R1** [AniAPI-Team/AniAPI#98]
When i click on the link in the readme i can't access to the doc

**Comment by Djihanegh** [comment]
Can you please provide docs ?, we really need it, thanks

**Comment by EL-R1** [comment]
> Can you please provide docs ?, we really need it, thanks

For waiting the doc of this api you can use this one

https://github.com/Tajikarao/livechart.me-rest-api

**Comment by DazornSama** [comment]
> When i click on the link in the readme i can't access to the doc

Fixed link

> Can you please provide docs ?, we really need it, thanks

If you need docs, you can host yourself [AniAPI-Docs](https://github.com/AniAPI-Team/AniAPI-Docs) docusaurus project
