### ISSUE TITLE
[BUG] Can't access website, raising a "Connection Time-out behaviour."

### ISSUE THREAD

**Issue by dwnppoalt** [AniAPI-Team/AniAPI#99]
I can't seem to access the website. Is it down currently? I tried connecting to it using `requests` in Python, and it raises the same error.

[Full screenshot when going to the website](https://ibb.co/RbXVXmh)

**FULL TRACEBACK:**
```Traceback (most recent call last):
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000025B93B5F910>, 'Connection to aniapi.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='aniapi.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025B93B5F910>, 'Connection to aniapi.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "x:\pyracy\test.py", line 5, in <module>
    r = requests.get(url)
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='aniapi.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025B93B5F910>, 'Connection to aniapi.com timed out. (connect timeout=None)'))```

**Comment by DazornSama** [comment]
> I can't seem to access the website. Is it down currently? I tried connecting to it using `requests` in Python, and it raises the same error.
> 
> [Full screenshot when going to the website](https://ibb.co/RbXVXmh)
> 
> **FULL TRACEBACK:**
> 
> ```
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
>     raise err
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
>     sock.connect(sa)
> TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
>     httplib_response = self._make_request(
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
>     self._validate_conn(conn)
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
>     conn.connect()
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 358, in connect
>     self.sock = conn = self._new_conn()
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
>     raise ConnectTimeoutError(
> urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000025B93B5F910>, 'Connection to aniapi.com timed out. (connect timeout=None)')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
>     resp = conn.urlopen(
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
>     retries = retries.increment(
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='aniapi.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025B93B5F910>, 'Connection to aniapi.com timed out. (connect timeout=None)'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "x:\pyracy\test.py", line 5, in <module>
>     r = requests.get(url)
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
>     return request("get", url, params=params, **kwargs)
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\Users\berio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 553, in send
>     raise ConnectTimeout(e, request=request)
> requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='aniapi.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025B93B5F910>, 'Connection to aniapi.com timed out. (connect timeout=None)'))```
> ```

Public APIs have been shutted down.
